stages:
    - release


release:
    stage: release
    image: "alpine"
    script:
        - apk add --update bash bash-completion python3 python3-dev gzip tar
        - pip3 install -U gitlab-release
        - gitlab-release --zip "release-${CI_COMMIT_SHORT_SHA}.zip" *
